#!/usr/bin/env python3
"""Small, hash-pinned ELF adaptations; never edit upstream sources in place."""
from __future__ import annotations
import argparse
import hashlib
import re
from pathlib import Path

BLOBS = {
    'io.cpp': 'df1eea065a6dead4132a1e303a1dc1938a643099',
    'runtime.cpp': '11b17bb40159b87538ada7fd63888ff54edf0da0',
    'backup.cpp': '85ff35dbdc8c15852a6a4df6fee8814dba0f9c1b',
}
CAPTURED = {
    'runtime.cpp': ('data_020a6460[8]', 'data_020a60c4[8]'),
    'backup.cpp': ('data_port_backup_device[10]', 'data_020a4b40[8]',
                   'data_020a8160[8]', 'g_port_backup_fill'),
}

def once(text: str, old: str, new: str) -> str:
    if text.count(old) != 1:
        raise ValueError(f'Expected exactly one reviewed anchor: {old!r}')
    return text.replace(old, new, 1)

def adapt_text(name: str, text: str) -> str:
    if name == 'io.cpp':
        text = once(text, 'char namebuf[MAX_PATH];', 'char namebuf[PATH_MAX];')
        return '#include <limits.h>\n' + text
    if name not in CAPTURED:
        raise ValueError(f'Unsupported source: {name}')
    text, count = re.subn(r'^#include [<"][^>"\n]*dsstate_seg\.h[>"]\s*$',
                          '#include "sm64ds_state_section.h"', text, flags=re.M)
    if count != 1:
        raise ValueError('Expected one DSSTATE header')
    text = once(text, '\nDSSTATE_BEGIN\n', '\n// Audited globals use explicit ELF section attributes below.\n')
    text = once(text, '\nDSSTATE_END\n', '\n// End of audited NTR state globals.\n')
    for symbol in CAPTURED[name]:
        # Include the following punctuation to avoid matching comments or uses.
        for suffix in (';', ' ='):
            old = symbol + suffix
            if text.count(old) == 1:
                text = once(text, old, symbol + ' SM64DS_CAPTURED' + suffix)
                break
        else:
            raise ValueError(f'Missing/ambiguous definition for {symbol}')
    return text

def generate(source: Path, output: Path) -> None:
    raw = source.read_bytes()
    got = hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).hexdigest()
    expected = BLOBS.get(source.name)
    if expected is None or got != expected:
        raise ValueError(f'Unreviewed {source.name}: expected {expected}, received {got}')
    if source.resolve() == output.resolve():
        raise ValueError('Refusing to edit the upstream source in place')
    result = adapt_text(source.name, raw.decode('utf-8'))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('// Generated by android/engine/tools/adapt_ntr.py.\n' + result, encoding='utf-8')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    try:
        generate(args.source, args.output)
    except (OSError, UnicodeError, ValueError) as exc:
        parser.exit(1, f'error: {exc}\n')
