#!/usr/bin/env python3
"""Generate a portable copy of link100's frame loop; never edit decomp sources."""
from __future__ import annotations
import argparse
from pathlib import Path


def adapt(text: str) -> str:
    windows = '#if defined(_WIN32)\n#define WIN32_LEAN_AND_MEAN\n#include <windows.h>\n#endif'
    if text.count(windows) != 1:
        raise ValueError('Unexpected Windows include block. Review the upstream runtime before adapting it.')
    text = text.replace(windows, '@@SM64DS_WINDOWS_INCLUDE@@', 1)
    # There are exactly two Windows-only blocks: the trampoline and VBlank wait.
    gate = '#if defined(_WIN32)'
    if text.count(gate) != 2 or text.count('#if !defined(_WIN32)') != 1:
        raise ValueError('Unexpected runtime platform guards; refusing a blind replacement.')
    text = text.replace(gate, '#if defined(_WIN32) || defined(SM64DS_NATIVE_FIBERS)')
    text = text.replace('#if !defined(_WIN32)', '#if !defined(_WIN32) && !defined(SM64DS_NATIVE_FIBERS)')
    text = text.replace('@@SM64DS_WINDOWS_INCLUDE@@', windows[:-6] + '#elif defined(SM64DS_NATIVE_FIBERS)\n#include "win_fiber_compat.h"\n#endif')
    # The upstream error path leaves the host thread converted if CreateFiber fails.
    fail = 'std::fprintf(stderr, "rt_run: CreateFiber failed\\n");\n        return 0;'
    if text.count(fail) != 1:
        raise ValueError('Unexpected CreateFiber cleanup block.')
    text = text.replace(fail, 'std::fprintf(stderr, "rt_run: CreateFiber failed\\n");\n        ConvertFiberToThread();\n        return 0;', 1)
    return '// Generated by android/native/tools/adapt_runtime.py. Do not edit.\n' + text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    result = adapt(args.source.read_text(encoding='utf-8'))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(result, encoding='utf-8')


if __name__ == '__main__':
    main()
